### ISSUE TITLE
First Week Task

### ISSUE THREAD

**Issue by xprilion** [pujam1231/Human-Pose-Estimation#1]
Hi @pujam1231, great work with the first week task!

I was trying to run the notebook, however I got the following error - 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-6b9f52b4d81c> in <module>
      8 imageid = str(person_kepypoint_val['annotations'][0]['image_id'])
      9 fin_id= ""
---> 10 for x in range(12-len(exampleimg)):
     11   fin_id += '0'
     12 

NameError: name 'exampleimg' is not defined
```

at the 6th block of code. Can you please check and rectify, I'm sure its a small issue. I shall continue with the evaluation then :)

**Comment by pujam1231** [comment]
Hi,

My apologies for the late response. Everything should be fixed now!

Thanks,
Puja M.

**Comment by xprilion** [comment]
Thanks for fixing this, the code works fine and correctly. Could you also try to display the skeleton of the recognized humanoid shape? That would be a great to have feature!

**Comment by xprilion** [comment]
Hi @pujam1231, I can see you've updated the code to address the issue. Thanks for doing that! I'll go ahead and mark it closed. Congratulations on completing the first-week task! Good luck with the next one, I find it very testing for me! :smiley: 

PS: You can reply to the issue comments to let me know if you're done working with them or need some clarification!
